### ISSUE TITLE
Running the loader a 2nd time breaks when running against a cloud managed cluster (elastic.co)

### ISSUE THREAD

**Issue by MilesNorton** [mountain-pass/addressr#388]
I have an elasticsearch managed cluster on elastic.co. When I run the loader function for the first time it runs but then when i run it again it breaks withe following error:
```
ResponseError: parse_exception: [parse_exception] Reason: mix of settings map and top-level properties
    at onBody (/home/miles-karmo/Projects/addressrio/node_modules/@opensearch-project/opensearch/lib/Transport.js:426:23)
    at IncomingMessage.onEnd (/home/miles-karmo/Projects/addressrio/node_modules/@opensearch-project/opensearch/lib/Transport.js:341:11)
    at IncomingMessage.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) 
```

At the moment I need to drop the index and re-sync everything which takes time since I won't be able to run the loader function per state as well.

**Comment by tompahoward** [comment]
We don't have an elastic.co account to reproduce and verify a fix against. AWS OpenSearch is the supported managed cluster option. If you're able to try that instead, let us know if the issue reproduces there.

If switching isn't an option, dropping the index and re-running the loader will unblock you.

**Comment by tompahoward** [comment]
Our AWS OpenSearch setup (which our CI pipelines run against) does not reproduce this. The loader runs correctly on repeated invocations there.

The issue is specific to how elastic.co handles the index settings update request. It may be a stricter API version or different body parsing compared to OpenSearch.

Without an elastic.co account we can't reproduce or verify a fix. Closing: can't reproduce on a supported config. If the Elasticsearch version elastic.co is running points to something we can address, reopen with the details.
