### ISSUE TITLE
SCHEMA_VALIDATION_FAILED if you follow the Quick Start guide

### ISSUE THREAD

**Issue by koresar** [mountain-pass/addressr#7]
Following this: https://github.com/mountain-pass/addressr/blob/master/README.md

Data loader went fine on my machine. Took half an hour but it works.

Item 7:
```
curl -i http://localhost:8080/addresses?q=LEVEL+25,+TOWER+3
```
Returns:
```
HTTP/1.1 500 Internal Server Error
X-Powered-By: Express
Content-Type: application/json; charset=utf-8
Content-Length: 431
ETag: W/"2-vyGp6PvFo4RvsFtPoIWeCReyIC8"
Date: Wed, 19 Aug 2020 01:49:25 GMT
Connection: keep-alive

{
  "code": "SCHEMA_VALIDATION_FAILED",
  "failedValidation": true,
  "originalResponse": {},
  "message": "Response validation failed: failed schema validation",
  "errors": [
    {
      "code": "INVALID_TYPE",
      "message": "Expected type array but found type object",
      "path": [],
      "description": "The list of addresses matching the search string. The list may be paginated.\nA the `Link` header with a `rel` of `next` will be provied if there are addional results.\n"
    }
  ]
}
```

I can debug that myself you don't have time. But my Elasticsearch knowledge is near zero.

PS: There a typo in the word "provied" and "addional" in the error above. :)

**Comment by koresar** [comment]
I found the problem.

Everything works fine using this repo, but the error above occurs using the `@mountainpass/addressr` module.
The npm module published is different to the latest `master` branch.

**Comment by tompahoward** [comment]
Thanks. Looking into it.

**Comment by koresar** [comment]
I can see that npm module v1.0.**13** was published. But this `master` references v1.0.**14**. Could it be the issue?

**Comment by koresar** [comment]
In `utils/writer.js` I find that
`code===200`
but payload is this object:
```
TypeError: Cannot read property 'encodeUriFragmentIdentifier' of undefined
    at getAddresses (./node_modules/@mountainpass/addressr/lib/service/AddressService.js:1534:49)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by koresar** [comment]
I pretty much see what's the root cause.

The latest `json-ptr` module is `1.3.2`. Whereas between `json-ptr@1.1.2` and `json-ptr@1.3.2` there was a breaking change on how they export the main node module. (They rewrote it with TypeScript and did not bump the major version to 2. This is poor software maintenance practices.)

The fix is to make sure `addressr-server` is using `json-ptr@1.1.2`, the latest non-TS version.

```
npm i json-ptr@1.1.2
```

After that the server works as expected.

My recommendation. Pinpoint in `package.json` the version of `json-ptr` to be exactly `1.1.2`.

**Comment by koresar** [comment]
The maintainer apologised :)
https://github.com/flitbit/json-ptr#breaking-changes-at-v130

**Comment by tompahoward** [comment]
Thanks for the awesome detective work. I'll try to get a new version out over the next couple of days, but it might take longer because of #6 .

**Comment by tompahoward** [comment]
Confirmed testes are failing when explicitly upgrading to json-ptr@1.3.2.

I'm trying to figure out why the tests didn't fail without the explicit upgrade.

**Comment by tompahoward** [comment]
> I can see that npm module v1.0.13 was published. But this master references v1.0.14. Could it be the issue?

When we publish, we tag the current revision of the code and then bum the version in master. This way master will  be in a release ready state, referring to the next publish version.
